### ISSUE TITLE
input status

### ISSUE THREAD

**Issue by Electroso** [instipod/HHCN8I8OP-MQTT#1]
Hello, 
I'm trying to get the input feedback but when I trigger the pushbutton I get it like 3 times:
Triggering input 8:
input10000000input00000000input10000000input00000000input10000000input00000000

Do you know what's happening?

**Comment by instipod** [comment]
It sounds like a debounce issue, which is common with push buttons.  See [this Arduino document](https://docs.arduino.cc/built-in-examples/digital/Debounce) for more information about debounce.  I'm not sure if the HHCN8I8OP has any options in the vendor provided tool to help debounce the input.  I'm using the device with dry contact outputs from another device, which doesn't seem to have false triggering.
